version: '3.9'

services:

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=secretsmanager,sqs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - './localSetup.sh/:/docker-entrypoint-initaws.d/localSetup.sh'

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'stock-crypto-reports'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - 'my-db:/var/lib/mysql'
      - './init.sql/:/docker-entrypoint-initdb.d/init.sql'

  application:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID="000000"
      - AWS_SECRET_ACCESS_KEY="000000"
    depends_on:
      - db

# Names our volume
volumes:
    my-db:

