version: '3.3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4563-4599:4563-4599'
#      - '8055:8080'
    environment:
      - SERVICES=secretsmanager,sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localSetup.sh/:/docker-entrypoint-initaws.d/localSetup.sh'

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'stock-crypto-reports'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
      - './init.sql/:/docker-entrypoint-initdb.d/init.sql'

#  application:
#    image: crypto-buyer
#    container_name: cryptobuyer
#    ports:
#      - '8080:8080'

# Names our volume
volumes:
    my-db:
