version: '3.9'

services:

  datadog:


  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=secretsmanager,sqs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - './localSetup.sh/:/docker-entrypoint-initaws.d/localSetup.sh'
    networks:
      - datadog-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'stock-crypto-reports'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - 'my-db:/var/lib/mysql'
      - './init.sql/:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - datadog-network

  application:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID="000000"
      - AWS_SECRET_ACCESS_KEY="000000"
    depends_on:
      - db
    networks:
      - datadog-network

# Names our volume
volumes:
    my-db:

networks:
  datadog-network:
    name: datadog-network

