version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_aws
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=secretsmanager
      - DEFAULT_REGION=us-east-1
    volumes:
      - './localSetup.sh/:/docker-entrypoint-initaws.d/localSetup.sh'